# [STUDENT TASK]
# Write a multi-stage Dockerfile here to build a lightweight image.
# Requirements:
# 1. Base image should be small (e.g. debian:slim, python:3.X-slim)
# 2. DO NOT COPY the model weights into this image.
# 3. Use multi-stage builds to compile/install dependencies without including build tools in the final image.

FROM scratch
# ... your code here ...
